name: Feature request
description: Suggest a new check, flag, or improvement
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem or motivation
      description: What problem does this feature solve? Why is it useful?
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed solution
      description: Describe what you'd like to see. Include examples if possible.
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative approaches you've thought about.
    validations:
      required: false
